import type { ColorPalette } from "@/types/design";

const STATUS = { statusPaid: "#16A34A", statusPending: "#D97706", statusOverdue: "#DC2626" };
const LIGHT_CHROME = { headerBg: "#FFFFFF", footerBg: "#F8FAFC", border: "#E5E7EB" };

export const BUILTIN_PALETTES: ColorPalette[] = [
  {
    id: "ocean-blue",
    name: "Ocean Blue",
    primary: "#0EA5E9",
    secondary: "#0369A1",
    accent: "#38BDF8",
    tableHeaderBg: "#EFF8FF",
    icon: "#0EA5E9",
    text: "#0F172A",
    muted: "#64748B",
    ...LIGHT_CHROME,
    ...STATUS,
  },
  {
    id: "royal-blue",
    name: "Royal Blue",
    primary: "#2563EB",
    secondary: "#1E3A8A",
    accent: "#60A5FA",
    tableHeaderBg: "#EEF2FF",
    icon: "#2563EB",
    text: "#0F172A",
    muted: "#64748B",
    ...LIGHT_CHROME,
    ...STATUS,
  },
  {
    id: "midnight-black",
    name: "Midnight Black",
    primary: "#18181B",
    secondary: "#3F3F46",
    accent: "#A1A1AA",
    headerBg: "#18181B",
    footerBg: "#F4F4F5",
    tableHeaderBg: "#F4F4F5",
    border: "#E4E4E7",
    icon: "#18181B",
    text: "#18181B",
    muted: "#71717A",
    ...STATUS,
  },
  {
    id: "emerald",
    name: "Emerald",
    primary: "#10B981",
    secondary: "#047857",
    accent: "#6EE7B7",
    tableHeaderBg: "#ECFDF5",
    icon: "#10B981",
    text: "#0F172A",
    muted: "#64748B",
    ...LIGHT_CHROME,
    ...STATUS,
  },
  {
    id: "forest-green",
    name: "Forest Green",
    primary: "#166534",
    secondary: "#14532D",
    accent: "#4ADE80",
    tableHeaderBg: "#F0FDF4",
    icon: "#166534",
    text: "#14261B",
    muted: "#57705F",
    ...LIGHT_CHROME,
    ...STATUS,
  },
  {
    id: "modern-purple",
    name: "Modern Purple",
    primary: "#7C3AED",
    secondary: "#5B21B6",
    accent: "#C4B5FD",
    tableHeaderBg: "#F5F3FF",
    icon: "#7C3AED",
    text: "#1E1B2E",
    muted: "#6B647E",
    ...LIGHT_CHROME,
    ...STATUS,
  },
  {
    id: "sunset-orange",
    name: "Sunset Orange",
    primary: "#F97316",
    secondary: "#C2410C",
    accent: "#FDBA74",
    tableHeaderBg: "#FFF7ED",
    icon: "#F97316",
    text: "#1C1917",
    muted: "#78716C",
    ...LIGHT_CHROME,
    ...STATUS,
  },
  {
    id: "business-gray",
    name: "Business Gray",
    primary: "#475569",
    secondary: "#1E293B",
    accent: "#94A3B8",
    tableHeaderBg: "#F1F5F9",
    icon: "#475569",
    text: "#0F172A",
    muted: "#64748B",
    ...LIGHT_CHROME,
    ...STATUS,
  },
  {
    id: "luxury-gold",
    name: "Luxury Gold",
    primary: "#B45309",
    secondary: "#78350F",
    accent: "#FCD34D",
    headerBg: "#1C1917",
    footerBg: "#FAF5EB",
    tableHeaderBg: "#FAF5EB",
    border: "#E7DCC5",
    icon: "#B45309",
    text: "#1C1917",
    muted: "#78716C",
    ...STATUS,
  },
  {
    id: "navy",
    name: "Navy",
    primary: "#1E3A5F",
    secondary: "#0F1F33",
    accent: "#60A5FA",
    headerBg: "#0F1F33",
    footerBg: "#F8FAFC",
    tableHeaderBg: "#EFF4FA",
    border: "#DCE4EE",
    icon: "#1E3A5F",
    text: "#0F172A",
    muted: "#64748B",
    ...STATUS,
  },
  {
    id: "white-minimal",
    name: "White Minimal",
    primary: "#18181B",
    secondary: "#52525B",
    accent: "#D4D4D8",
    tableHeaderBg: "#FAFAFA",
    icon: "#18181B",
    text: "#18181B",
    muted: "#71717A",
    headerBg: "#FFFFFF",
    footerBg: "#FFFFFF",
    border: "#EDEDF0",
    ...STATUS,
  },
  {
    id: "professional-dark",
    name: "Professional Dark",
    primary: "#818CF8",
    secondary: "#A5B4FC",
    accent: "#6366F1",
    headerBg: "#111827",
    footerBg: "#111827",
    tableHeaderBg: "#1F2937",
    border: "#374151",
    icon: "#818CF8",
    text: "#F4F4F5",
    muted: "#A1A1AA",
    ...STATUS,
  },
];

export function getPalette(id: string): ColorPalette {
  return BUILTIN_PALETTES.find((p) => p.id === id) ?? BUILTIN_PALETTES[0]!;
}
